[env:ATtiny3227]
platform = atmelmegaavr
board = ATtiny3227
framework = arduino
board_build.core = megatinycore
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal

lib_deps =
    jgromes/RadioLib @ ^6.6.0
    adafruit/Adafruit GPS Library@^1.7.5
    adafruit/Adafruit SGP30 Sensor@^2.0.3
    gabrielnotman/CryptoAuthLib@^1.0.1

build_flags =
    -D LOG_RADIO=true
    -D LOG_SYSINFO=true
    -D I2CDEV=1
    -D KEY=\"abcdefghijklmnop\"
    -D LOG_AQ=true
    -D LOG_AQ_INTERVAL_S=600
    -DHAVE_HWSERIAL1
    -DNO_SW_SERIAL
    -I $PROJECT_DIR/lib/SoftwareSerial
    -include $PROJECT_DIR/lib/SoftwareSerial/SoftwareSerial.h

; --- ADAFRUIT GPS HARDWARE DE-ALLOCATIONS ---
    -D GPS_MAX_SATELLITES=1          ; Reclaims ~500 bytes of RAM tracking space
    -D NMEA_MAX_SENTENCE_LENGTH=70   ; Drops active string buffers to the bare minimum spec
    -D NMEA_COMPAT_ONLY              ; Disables optional background status tracking metadata

; --- RADIOLIB HARDWARE DE-ALLOCATIONS ---
    -D RADIOLIB_EXCEPT_DIRECT_RECEPTION ; Reclaims ~300 bytes of global statics
    -D RADIOLIB_EXCEPT_TRNG             ; Strips out internal True Random Number buffers
