[env:ATtiny3227]
platform = atmelmegaavr
board = ATtiny3227
framework = arduino
board_build.core = megatinycore
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal

lib_deps =
    jgromes/RadioLib @ ^6.6.0

build_flags = 
    -D LOG_RADIO=true
    -D LOG_SYSINFO=true